In [13]:
import numpy as np

EX1:
Write a python function, named time_to_array_addition the function gets as input an array or a list. Check the type and adds 1 to each argument in the array list and prints the time it took.

In [14]:
import numpy as np
import time

def time_to_array_addition(data):
    # 1.input type
    input_type = type(data)
    print(f"Input type: {input_type}")

    # 2. start time
    start_time = time.time()

    # 3. Perform the addition based on type
    if isinstance(data, np.ndarray):
        # NumPy Arr
        result = data + 1
    elif isinstance(data, list):
        # Standard list
        result = [x + 1 for x in data]
    else:
        print("Unsupported type.")
        return

    # 4. end-time
    end_time = time.time()
    # 5. Calc duration
    duration = end_time - start_time

    print(f"Time taken: {duration:.8f} sec")
    return result

# --- Test---
#list
my_list = list(range(1000000))
time_to_array_addition(my_list)

# NumPy array
my_array = np.arange(1000000)
time_to_array_addition(my_array)

Input type: <class 'list'>
Time taken: 0.07557297 sec
Input type: <class 'numpy.ndarray'>
Time taken: 0.00173879 sec

array([      1,       2,       3, ...,  999998,  999999, 1000000])

In [15]:
%who

arr1	 df	 ex2	 i	 kagglehub	 my_array	 my_list	 np	 path
pd	 random	 time	 time_to_array_addition

# EX2:
write a function named ex2 that takes an array finds it's maximum value and than create a new array from zero to maximum value in steps of 3

In [16]:
import random

def ex2(arr):
  max = np.max(arr)

  return np.arange(0,max,3)

arr1 = np.empty(10)

for i in range(len(arr1)):
  arr1[i] = random.randint(0,50)

print(arr1)
print(ex2(arr1))

[45. 29. 17. 32.  9.  7. 46. 27. 41. 44.]
[ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33. 36. 39. 42. 45.]

# PANDAS

In [17]:
import pandas as pd

In [18]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("heptapod/titanic")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'titanic' dataset.
Path to dataset files: /kaggle/input/titanic

In [19]:
df = pd.read_csv("/kaggle/input/titanic/train_and_test2.csv")

In [20]:
df.head(1)

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.25,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Passengerid  1309 non-null   int64
 1   Age          1309 non-null   float64
 2   Fare         1309 non-null   float64
 3   Sex          1309 non-null   int64
 4   sibsp        1309 non-null   int64
 5   zero         1309 non-null   int64
 6   zero.1       1309 non-null   int64
 7   zero.2       1309 non-null   int64
 8   zero.3       1309 non-null   int64
 9   zero.4       1309 non-null   int64
 10  zero.5       1309 non-null   int64
 11  zero.6       1309 non-null   int64
 12  Parch        1309 non-null   int64
 13  zero.7       1309 non-null   int64
 14  zero.8       1309 non-null   int64
 15  zero.9       1309 non-null   int64
 16  zero.10      1309 non-null   int64
 17  zero.11      1309 non-null   int64
 18  zero.12      1309 non-null   int64
 19  zero.13      1309 non-null   int64
 20  zero.14      1309 non-null   int64
 21  Pclass       1309 non-null   int64
 22  zero.15      1309 non-null   int64
 23  zero.16      1309 non-null   int64
 24  Embarked     1307 non-null   float64
 25  zero.17      1309 non-null   int64
 26  zero.18      1309 non-null   int64
 27  2urvived     1309 non-null   int64
dtypes: float64(3), int64(25)
memory usage: 286.5 KB

In [22]:
df.isna().sum()

Passengerid    0
Age            0
Fare           0
Sex            0
sibsp          0
zero           0
zero.1         0
zero.2         0
zero.3         0
zero.4         0
zero.5         0
zero.6         0
Parch          0
zero.7         0
zero.8         0
zero.9         0
zero.10        0
zero.11        0
zero.12        0
zero.13        0
zero.14        0
Pclass         0
zero.15        0
zero.16        0
Embarked       2
zero.17        0
zero.18        0
2urvived       0
dtype: int64

In [23]:
age_column = df["Age"]
age_column

0       22.0
1       38.0
2       26.0
3       35.0
4       35.0
        ...
1304    28.0
1305    39.0
1306    38.5
1307    28.0
1308    28.0
Name: Age, Length: 1309, dtype: float64

In [24]:
df_small = df[["Passengerid","Age","2urvived"]]
df_small

      Passengerid   Age  2urvived
0               1  22.0         0
1               2  38.0         1
2               3  26.0         1
3               4  35.0         1
4               5  35.0         0
...           ...   ...       ...
1304         1305  28.0         0
1305         1306  39.0         0
1306         1307  38.5         0
1307         1308  28.0         0
1308         1309  28.0         0

[1309 rows x 3 columns]

In [25]:
df.columns

Index(['Passengerid', 'Age', 'Fare', 'Sex', 'sibsp', 'zero', 'zero.1',
       'zero.2', 'zero.3', 'zero.4', 'zero.5', 'zero.6', 'Parch', 'zero.7',
       'zero.8', 'zero.9', 'zero.10', 'zero.11', 'zero.12', 'zero.13',
       'zero.14', 'Pclass', 'zero.15', 'zero.16', 'Embarked', 'zero.17',
       'zero.18', '2urvived'],
      dtype='object')

In [26]:
df.index

RangeIndex(start=0, stop=1309, step=1)

In [27]:
df.iloc[20]

Passengerid    21.0
Age            35.0
Fare           26.0
Sex             0.0
sibsp           0.0
zero            0.0
zero.1          0.0
zero.2          0.0
zero.3          0.0
zero.4          0.0
zero.5          0.0
zero.6          0.0
Parch           0.0
zero.7          0.0
zero.8          0.0
zero.9          0.0
zero.10         0.0
zero.11         0.0
zero.12         0.0
zero.13         0.0
zero.14         0.0
Pclass          2.0
zero.15         0.0
zero.16         0.0
Embarked        2.0
zero.17         0.0
zero.18         0.0
2urvived        0.0
Name: 20, dtype: float64

In [28]:
df_small.corr()

             Passengerid       Age  2urvived
Passengerid     1.000000  0.025799 -0.331493
Age             0.025799  1.000000 -0.055862
2urvived       -0.331493 -0.055862  1.000000

# EX3:
load the titanic dataset, calculate the correlations, and print the correlation between the passengerid and 2urvived

In [30]:
corr = df_small.corr()
res = corr['Passengerid'].iloc[2]
res

np.float64(-0.331493030924206)

In [31]:
corr.iloc[0, 0] # Works by index like indixing in lists/arrays
corr.loc["Passengerid", "Age"] # works based on columns and rows names

np.float64(0.025798517148073012)

# EX4
Check the correlation between the Fare and the Pclass, and the correlation between survived and Sex. Finally print which is higher

In [33]:
df = df[["Passengerid", 'Age', 'Fare', 'Sex', 'sibsp', 'Pclass', '2urvived']] # this will override the df variable
df_new = df.rename(columns={"2urvived": "Survived"}) # Renames the columns from key to value
df_new.head()

   Passengerid   Age     Fare  Sex  sibsp  Pclass  Survived
0            1  22.0   7.2500    0      1       3         0
1            2  38.0  71.2833    1      1       1         1
2            3  26.0   7.9250    1      0       3         1
3            4  35.0  53.1000    1      1       1         1
4            5  35.0   8.0500    0      0       3         0

In [40]:
res1 = df_new.corr().loc['Fare', 'Pclass']
print(res1)
res2 = df_new.corr().loc['Survived', 'Sex']
print(res2)

np.max([abs(res1), abs(res2)])

-0.5586833572857136
0.4040200356653614

np.float64(0.5586833572857136)

#Homework

##numpy

1. Write a function that gets an argument n, checks if it's higher than 0 and than generates an array in that size of ones.

In [58]:
def create_array(n):
  if n > 0 :
    return np.ones(n)
  return None

num = random.randint(-10,50)
arr = create_array(num)

print(f'n= {num}')
arr

n= 36

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1.])

2. Write a function that gets an argument n, checks if it's higher than 0 and than generates an array in that size between 0 to n with step 2.

In [61]:
def arranged_array(n):
  if n > 0:
    return np.arange(0,n,2)
  return None

num = random.randint(-10,50)
arr = arranged_array(num)

#test
print(f'n= {num}')
arr

n= 18

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

3. Write a python function that takes to arrays and calculates their correaltion hint: Numpy already implemented everything!

In [73]:
def arrs_corr(arr1,arr2):
  return np.correlate(arr1,arr2)

def build_array(n):
  arr = np.empty(n)
  for i in range(len(arr)):
    arr[i] = random.randint(-100,100)/100
  return arr

#test
arr1 = build_array(20)
arr2 = build_array(20)
print(f'arr1 = {arr1}')
print(f'arr2 = {arr2}')
print(f'Corralation: {arrs_corr(arr1,arr2)}')

arr1 = [-0.45 -0.44 -0.88  0.27  0.16  0.35 -0.72 -0.8  -0.54  0.24 -0.19 -0.38
  1.    0.51  0.16 -0.37 -0.05  0.97 -0.38 -0.98]
arr2 = [ 0.34 -0.42  0.66 -0.64  0.82  0.72  0.03 -0.05 -0.12 -0.27 -0.55  0.01
 -0.29  0.04 -0.38 -0.11  0.97 -0.28 -0.69  0.32]
Corralation: [-0.8807]

4. Write a python function that takes two arrays and checks if all the elements are equal

In [76]:
def is_equal_arr(arr1, arr2):
  return np.array_equal(arr1,arr2)

#test
arr1 = [1,6,8,3,5]
arr2 = [6,8,3,5,1]

print(is_equal_arr(arr1,arr2))

arr3 = [1,1,3,6,9]
arr4 = [1,1,3,6,9]

print(is_equal_arr(arr1,arr3))
print(is_equal_arr(arr4,arr3))

False
False
True

5. Write a python function that takes two arrays and checks if they contain the same variables not neccesserly in the same order

In [82]:
def is_same_orgs(arr1, arr2):
  return np.array_equal(np.sort(arr1), np.sort(arr2))


#test
arr1 = [1,6,8,3,5]
arr2 = [6,8,3,5,1]

print(is_same_orgs(arr1,arr2))

arr3 = [1,1,3,6,9]
arr4 = [1,1,3,6,9]

print(is_same_orgs(arr1,arr3))
print(is_same_orgs(arr4,arr3))

True
False
True

## Pandas

In [83]:
df.describe()

,Passengerid,Age,Fare,Sex,sibsp,Pclass,2urvived
count,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000
mean,655.000000,29.503186,33.281086,0.355997,0.498854,2.294882,0.261268
std,378.020061,12.905241,51.741500,0.478997,1.041658,0.837836,0.439494
min,1.000000,0.170000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,328.000000,22.000000,7.895800,0.000000,0.000000,2.000000,0.000000
50%,655.000000,28.000000,14.454200,0.000000,0.000000,3.000000,0.000000
75%,982.000000,35.000000,31.275000,1.000000,1.000000,3.000000,1.000000
max,1309.000000,80.000000,512.329200,1.000000,8.000000,3.000000,1.000000

1. Find the maximum value of each feature

In [85]:
df.max()

Passengerid    1309.0000
Age              80.0000
Fare            512.3292
Sex               1.0000
sibsp             8.0000
Pclass            3.0000
2urvived          1.0000
dtype: float64

2. Filter the table to only the rows where the sex column is 0

In [89]:
df.query('Sex == 0')

      Passengerid   Age      Fare  Sex  sibsp  Pclass  2urvived
0               1  22.0    7.2500    0      1       3         0
4               5  35.0    8.0500    0      0       3         0
5               6  28.0    8.4583    0      0       3         0
6               7  54.0   51.8625    0      0       1         0
7               8   2.0   21.0750    0      3       3         0
...           ...   ...       ...  ...    ...     ...       ...
1298         1299  50.0  211.5000    0      1       1         0
1304         1305  28.0    8.0500    0      0       3         0
1306         1307  38.5    7.2500    0      0       3         0
1307         1308  28.0    8.0500    0      0       3         0
1308         1309  28.0   22.3583    0      1       3         0

[843 rows x 7 columns]

3. Filter the table to only the rows where Age is above 70

In [107]:
df_70 = df.query('Age > 70')
df_70

     Passengerid   Age     Fare  Sex  sibsp  Pclass  2urvived
96            97  71.0  34.6542    0      0       1         0
116          117  70.5   7.7500    0      0       3         0
493          494  71.0  49.5042    0      0       1         0
630          631  80.0  30.0000    0      0       1         1
851          852  74.0   7.7750    0      0       3         0
987          988  76.0  78.8500    1      1       1         0

4. Filter the table to only the rows where Age is above 70 or below 15

In [106]:
df.query('Age > 70 or Age < 15')

      Passengerid   Age     Fare  Sex  sibsp  Pclass  2urvived
7               8   2.0  21.0750    0      3       3         0
9              10  14.0  30.0708    1      1       2         1
10             11   4.0  16.7000    1      1       3         1
14             15  14.0   7.8542    1      0       3         0
16             17   2.0  29.1250    0      4       3         0
...           ...   ...      ...  ...    ...     ...       ...
1251         1252  14.5  69.5500    0      8       3         0
1270         1271   5.0  31.3875    0      4       3         0
1280         1281   6.0  21.0750    0      3       3         0
1283         1284  13.0  20.2500    0      0       3         0
1300         1301   3.0  13.7750    1      1       3         0

[115 rows x 7 columns]

5. Check the precent of the previous group survival rate from the last question and compare it to the entire dataset. Is it better or worse?
survival rate = number of people survived / number of people

In [116]:
df = df.rename(columns={"2urvived": "Survived"}) # Renames the columns from key to value
df.head()
df_70 = df.query('Age > 70')
df_70

     Passengerid   Age     Fare  Sex  sibsp  Pclass  Survived
96            97  71.0  34.6542    0      0       1         0
116          117  70.5   7.7500    0      0       3         0
493          494  71.0  49.5042    0      0       1         0
630          631  80.0  30.0000    0      0       1         1
851          852  74.0   7.7750    0      0       3         0
987          988  76.0  78.8500    1      1       1         0

In [143]:
total_70_count = df_70['Passengerid'].count()
surv_70_count = df_70.query('Survived == 1')['Passengerid'].count()
survival_rate_70 = surv_70_count*100/total_70_count

print(f'total_70_count : {total_70_count}, surv_70_count : {surv_70_count}  , survival_rate_70: {survival_rate_70} ')

total_count = df['Passengerid'].count()
surv_count = df.query('Survived == 1')['Passengerid'].count()
survival_rate = surv_count*100/total_count

print(f'total_count : {total_count}, surv_count : {surv_count}  , survival_rate: {survival_rate} ')

max(survival_rate_70,survival_rate)

total_70_count : 6, surv_70_count : 1  , survival_rate_70: 16.666666666666668
total_count : 1309, surv_count : 342  , survival_rate: 26.12681436210848

np.float64(26.12681436210848)